### ISSUE TITLE
usage question for OS startup

### ISSUE THREAD

**Issue by joeblew99** [jpillora/overseer#1]
this looks really useful.
In my use case i typically need to install 3 binaries onto a machine.
web server, app server and maybe e another tool.
Now each one needs the other, so you have a graph.
with your system, each individual app would pull their updates and upgrade.
But what about the graph knowledge of each ? 
There seems to be two choices here:
1. Forget the graph and let each binary process self update independently
2. Root one upgrades, and tells the others to shutdown and upgrade 

Just thinking this through... and wondering what your thinking about dependency chains like this simple example.

**Comment by jpillora** [comment]
I think binary dependency management is out of this project's scope. Binary dependencies are probably best handled by something like [systemd](https://wiki.archlinux.org/index.php/systemd) (see [handling dependencies](https://wiki.archlinux.org/index.php/systemd#Handling_dependencies)).
