### ISSUE TITLE
Timeout. Forceful shutdown.

### ISSUE THREAD

**Issue by spaiz** [jpillora/overseer#10]
Hi. I'm trying use your package with no success.
Debian 8

If I starting my server, and don't do any http request, and then run Kkill cmd I get:

[overseer slave#1] run
[overseer slave#1] start program
some output from my program
`sudo kill -SIGUSR2 PID`
[overseer slave#1] graceful shutdown requested
[overseer master] proxy signal (user defined signal 1)
[overseer master] prog exited with 0

But, if I start the server, and do at least one http request, and then run kill cmd, the program exiting after timeout:

[overseer slave#1] run
[overseer slave#1] start program
some output from my program
```
wget http://locahost:PORT/api/
sudo kill -SIGUSR2 pid
```
[overseer slave#1] graceful shutdown requested
[overseer master] proxy signal (user defined signal 1)
[overseer slave#1] timeout. forceful shutdown
[overseer master] prog exited with 1

Ant ideas?

My main is:

```
func main() {
	overseer.Run(overseer.Config{
		Program: prog,
		Address: ":" + config.Port,
		Debug: true,
	})
}
```

My packages:

```
import (
	"net/http"
	"github.com/gorilla/mux"
	"fmt"
	"github.com/*/*/components"
	"runtime"
	"time"
	log "github.com/Sirupsen/logrus"
	"github.com/nytimes/gziphandler"
	"github.com/justinas/alice"
	"github.com/*/*/routers"
	"syscall"
	"github.com/jpillora/overseer"
 )
```

**Comment by jpillora** [comment]
Does the example work?

**Comment by spaiz** [comment]
Hi. Just played with example... It was my mistake...

In my app I was printing syscall.Getpid() to use it as signal receiver. If I send kill signal to PID from syscall.Getpid() as result my program will exit.

Now, to catch the most first PID I do:

```
var pfPath = "/var/run/myapp.pid"

func main() {
	pidfile.SetPidfilePath(pfPath)

	pid, err := pidfile.Read()

	if err != nil {
		fmt.Printf("err %v\n", err)
	}

	if (pid == 0) {
		pidfile.Write();
	}
```

Now If I do:

`kill -SIGUSR2 "$(cat /var/run/myapp.pid)"`

it looks working...
Hopefully it will help me to use it with systemd...

Thanks.
