### ISSUE TITLE
[Feature] Add TLS support

### ISSUE THREAD

**Issue by rafaeljusto** [jpillora/overseer#11]
Today when filling the Address of the overseer.Config type we open a TCP listener. It would be great to add [TLS support](https://golang.org/pkg/crypto/tls/#Listen).

**Comment by jpillora** [comment]
See https://golang.org/pkg/crypto/tls/#NewListener

```
tlsListener := tls.NewListener(tcpListener, tls.Config{ ... })
```

**Comment by rafaeljusto** [comment]
Thanks! :smile:
