### ISSUE TITLE
Call sync after mv?

### ISSUE THREAD

**Issue by lookfirst** [jpillora/overseer#22]
Thanks for a really awesome tool.

I'm running this on > 1000 little Pi servers that have various quality of flash storage and may reboot right in the middle of doing work.

Occasionally, I'll see either a corrupt file after an overseer upgrade or I'll see the file has zero bytes.

I'm thinking that calling `sync` after the `mv` will help with the corruption issues?

**Comment by jpillora** [comment]
Ah nice :)

I have seen this issue before, but as you mention - it's only occasionally
so it's hard to test. If you were to test with the added "sync", I'd be
happy to merge a PR!

**Comment by lookfirst** [comment]
@jpillora Agreed, nearly impossible to reliably test. PR submitted. Closing in favor of discussion around the PR. Can't really hurt to run it.
