### ISSUE TITLE
restarting

### ISSUE THREAD

**Issue by joeblew99** [jpillora/overseer#3]
Is there a way to code a golang app so that it can control its restarting itself ?

I have a bit of a russian doll situation where i need the golang code to do various things, rerestart with a different flag, do things, restart again with a different flag. You get the idea and its like a russian doll metaphor.

Super great package !! thanks for doing this.

I can test on arm v7 and v8 64 bit also soon.

**Comment by jpillora** [comment]
hey @joeblew99 just added a `overseer.Restart()` function to trigger a restart from within an app

**Comment by joeblew99** [comment]
i just tried it with your example. Wooooorks :)

I wil play around with it and let you know
