### ISSUE TITLE
Master gortoutine is blocked in handleSignal and SIGUSR1 doesn't work

### ISSUE THREAD

**Issue by xyzhu1120** [jpillora/overseer#31]
When Restarting is triggered, master process is blocked in select and as a result, it cannot handle sigusr1 from child process.
![image](https://user-images.githubusercontent.com/2072473/56746436-c9da2d00-67ae-11e9-8f31-ee6e0692719d.png)

![image](https://user-images.githubusercontent.com/2072473/56746709-55ec5480-67af-11e9-94b1-e98c1ab71272.png)

Can I create a new goroutine to call mp.triggerRestart() in func handleSignal

**Comment by mutexlock** [comment]
I have the same problem. How can fix it?

**Comment by mutexlock** [comment]
I send USR2 to master,  slave send  SIGUSR1 to master,but master  is blocked
