### ISSUE TITLE
[overseer master] proxy signal (broken pipe)

### ISSUE THREAD

**Issue by lihui-hub** [jpillora/overseer#40]
sometimes happen, how to do with this ?

[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)
[overseer master] proxy signal (broken pipe)

**Comment by jpillora** [comment]
Is it reproducible?

**Comment by jpillora** [comment]
Reopen with example please
