### ISSUE TITLE
"failed to run temp binary" on Windows

### ISSUE THREAD

**Issue by joshforbes** [jpillora/overseer#55]
Hello 👋

Thanks for the great library. It was simple to get it implemented in our code base. We have it working successfully on Mac but I'm running into a bit of trouble on Windows. We're using the HTTP fetcher which is downloading the file and placing it in a temp directory successfully (can see it show up in file explorer). But when the fetch process tries to see if the downloaded binary is executable it returns an error and bails out:

`failed to run temp binary: exec: "C:\\Users\\Level\\AppData\\Local\\Temp\\overseer-1dc5f76e2b9039ce": file does not exist (C:\Users\Level\AppData\Local\Temp\overseer-1dc5f76e2b9039ce) output ""`

The file certainly does exist but for some reason Go thinks it doesn't. The error is coming from this line: https://github.com/jpillora/overseer/blob/6877a7e73f6a4bebbfe1999fcbf84e52a3c1e6ca/proc_master.go#L287

![image](https://user-images.githubusercontent.com/3682518/86842203-db85b880-c072-11ea-810c-05875eb86129.png)

Does anyone have any experience or advice related to this error? Thanks!

**Comment by joshforbes** [comment]
Also, the file appears in file explorer and then short while later is deleted. I assume the delete happens after it fails to apply the update but don't know that for sure.

**Comment by joshforbes** [comment]
I got to root of this problem. Turns out it's because the temp binary doesn't have an extension and the PATHEXT env variable doesn't include "." by default. This issue could be fixed in user-land by adding that env variable when the program starts. But maybe the ideal solution would be for this package to be updated to either: make the temp binary an `exe` on Windows or to add "." to the PATHEXT before it tries to execute the temp file.

**Comment by jpillora** [comment]
hey @joshforbes, could you test `v1.1.5` - thanks for your help @tgulacsi

**Comment by joshforbes** [comment]
1.1.5 is great and fixes my other Windows problem (https://github.com/jpillora/overseer/issues/56). But does nothing for this one. The problem here is that the default PATHEXT for windows 10 is: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC` but the temp file doesn't have an extension.

https://superuser.com/a/1027081

Changing the PATHEXT to: `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.` (with a "." at the end for no extension files) makes it work.

I think we could likely change:

https://github.com/jpillora/overseer/blob/36ed46f9bcbd7314d3b5b0643b1d907adea775fe/proc_master.go#L22

To have an ".exe" extension on windows and it would fix the problem. Does that seem right?

**Comment by tgulacsi** [comment]
Sure, just not globally, but only on Windows.

**Comment by tgulacsi** [comment]
You should try 

```
--- a/proc_slave_windows.go
+++ b/proc_slave_windows.go
@@ -16,6 +16,10 @@ var (
        Timeout = 3 * time.Second
 )

+func init() {
+       tmpBinPath += ".exe"
+}
+
 type Win32_Process struct {
        Name                  string
        ExecutablePath        *string
```
